/**
 * generate.ts — Generate polymath extension artifacts from a tools.yaml descriptor
 * or from analysis of existing ArkTS files.
 *
 * Outputs:
 *   manifest.yaml               — polymath extension manifest
 *   manifest.ts                 — TypeScript import of manifest for registerExtension()
 *   PolybindExtension.ts        — Node.js IExtension wrapper (case 1 only)
 *   PolybindExtension.ets       — ArkTS IExtension wrapper (case 1 only, stamped from template)
 *
 * For case 2 (mixed) and case 3 (ArkTS only), manifest files are still generated,
 * but the wrappers are the fixed .ets files (not a new generated wrapper).
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { resolve, dirname, basename, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import yaml from 'js-yaml'

const __dir = dirname(fileURLToPath(import.meta.url))

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ToolsYaml {
  extension: {
    name: string
    version: string
    description?: string
    so_name: string         // NAPI module name; ArkTS import: `import X from 'libX.so'`
    platforms?: string[]
  }
  tools: Array<{
    name: string
    description: string
    input_schema: Record<string, unknown>
  }>
}

export interface ManifestTypeEntry {
  kind: string
  type: string
  description?: string
  platforms?: string[]
  schema?: Record<string, unknown>
}

export interface ManifestFile {
  name: string
  version: string
  description?: string
  types: ManifestTypeEntry[]
}

// ── Parse tools.yaml ─────────────────────────────────────────────────────────

export function parseToolsYaml(yamlPath: string): ToolsYaml {
  const raw = readFileSync(yamlPath, 'utf8')
  return yaml.load(raw) as ToolsYaml
}

// ── Generate manifest.yaml ────────────────────────────────────────────────────

export function buildManifest(descriptor: ToolsYaml): ManifestFile {
  return {
    name: descriptor.extension.name,
    version: descriptor.extension.version,
    description: descriptor.extension.description,
    types: [
      {
        kind: 'toolkit',
        type: descriptor.extension.name,
        description: descriptor.extension.description,
        platforms: descriptor.extension.platforms as ('node' | 'arkts')[],
        schema: {
          type: 'object',
          properties: {},
          additionalProperties: false,
        },
      },
    ],
  }
}

export function writeManifestYaml(manifest: ManifestFile, outDir: string): void {
  // Clean up undefined fields before serializing
  const clean = JSON.parse(JSON.stringify(manifest))
  const yamlStr = yaml.dump(clean, { lineWidth: 100 })
  writeFileSync(join(outDir, 'manifest.yaml'), yamlStr, 'utf8')
}

// ── Generate manifest.ts ──────────────────────────────────────────────────────

export function writeManifestTs(manifest: ManifestFile, outDir: string): void {
  const ts = `// GENERATED by polybind-codegen — do not edit manually.
import type { ExtensionManifestFile } from '@polymath/types'

export const manifest: ExtensionManifestFile = ${JSON.stringify(manifest, null, 2)} as const
`
  writeFileSync(join(outDir, 'manifest.ts'), ts, 'utf8')
}

// ── Generate PolybindExtension.ets (ArkTS wrapper, case 1) ───────────────────

export function writeArkTSWrapper(descriptor: ToolsYaml, outDir: string): void {
  const templatePath = resolve(__dir, '../../runtime/arkts/src/PolybindExtension.ets.tmpl')
  let tmpl = readFileSync(templatePath, 'utf8')

  const soName = descriptor.extension.so_name
  tmpl = tmpl.replaceAll('{{SO_NAME}}', soName)
  tmpl = tmpl.replaceAll('{{EXTENSION_NAME}}', descriptor.extension.name)
  tmpl = tmpl.replaceAll('{{EXTENSION_VERSION}}', descriptor.extension.version)

  writeFileSync(join(outDir, 'PolybindExtension.ets'), tmpl, 'utf8')
}

// ── Generate PolybindExtension.ts (Node.js wrapper, case 1) ──────────────────

export function writeNodeWrapper(descriptor: ToolsYaml, outDir: string): void {
  const soName = descriptor.extension.so_name
  const ts = `// GENERATED by polybind-codegen — do not edit manually.
// Node.js IExtension wrapper for polybind extension: ${descriptor.extension.name}
import { PolybindExtension as _PolybindExtension } from '@polybind/runtime-node'
import { manifest } from './manifest.js'
import { fileURLToPath } from 'node:url'
import { resolve, dirname } from 'node:path'

const __dir = dirname(fileURLToPath(import.meta.url))
// The .node file is expected at: <outDir>/../build/${soName}_node.node
// Adjust this path based on your CMake build output directory.
const nodePath = resolve(__dir, '../build/${soName}_node.node')

export const extension = new _PolybindExtension(nodePath)
export { manifest }
`
  writeFileSync(join(outDir, 'PolybindExtension.ts'), ts, 'utf8')
}

// ── Generate CMakeLists.txt (case 1) ─────────────────────────────────────────

export function writeCMakeLists(
  descriptor: ToolsYaml,
  srcDir: string,
  outDir: string,
  polybindRoot: string,
): void {
  const soName = descriptor.extension.so_name
  const sources = getCppSources(srcDir)
  // Use paths relative to the output CMakeLists.txt for portability
  const { relative } = require('node:path') as typeof import('node:path')
  const relSrc = relative(outDir, srcDir).replace(/\\/g, '/')
  const relPolybind = relative(outDir, polybindRoot).replace(/\\/g, '/')

  const cmake = `# GENERATED by polybind-codegen — do not edit manually.
cmake_minimum_required(VERSION 3.14)

# ── ArkTS: detect OHOS cross-compiler BEFORE project() ───────────────────────
if(POLYBIND_PLATFORM STREQUAL "arkts")
  if(NOT DEFINED OHOS_SDK_NATIVE OR OHOS_SDK_NATIVE STREQUAL "")
    if(DEFINED ENV{OHOS_SDK_NATIVE})
      set(OHOS_SDK_NATIVE "$ENV{OHOS_SDK_NATIVE}")
    else()
      foreach(_cand
        "/mnt/d/harmonyos/DevEco Studio/sdk/default/openharmony/native"
        "/mnt/c/Users/$ENV{USER}/AppData/Local/Huawei/Sdk/openharmony/native"
        "$ENV{HOME}/harmonyos/native"
      )
        if(EXISTS "\${_cand}/llvm/bin/clang" OR EXISTS "\${_cand}/llvm/bin/clang.exe")
          set(OHOS_SDK_NATIVE "\${_cand}")
          break()
        endif()
      endforeach()
    endif()
  endif()
  if(DEFINED OHOS_SDK_NATIVE AND NOT OHOS_SDK_NATIVE STREQUAL "")
    if(EXISTS "\${OHOS_SDK_NATIVE}/llvm/bin/clang")
      # Native Linux cross-compiler
      set(CMAKE_C_COMPILER   "\${OHOS_SDK_NATIVE}/llvm/bin/clang"   CACHE STRING "" FORCE)
      set(CMAKE_CXX_COMPILER "\${OHOS_SDK_NATIVE}/llvm/bin/clang++" CACHE STRING "" FORCE)
      set(CMAKE_C_COMPILER_TARGET   "aarch64-linux-ohos" CACHE STRING "" FORCE)
      set(CMAKE_CXX_COMPILER_TARGET "aarch64-linux-ohos" CACHE STRING "" FORCE)
      set(CMAKE_SYSROOT "\${OHOS_SDK_NATIVE}/sysroot" CACHE STRING "" FORCE)
      set(CMAKE_C_FLAGS_INIT   "-D__MUSL__")
      set(CMAKE_CXX_FLAGS_INIT "-D__MUSL__")
    elseif(EXISTS "\${OHOS_SDK_NATIVE}/llvm/bin/clang.exe")
      # Windows SDK running via WSL2 binfmt_misc — clang.exe needs Windows-style sysroot path
      string(REGEX REPLACE "^/mnt/([a-zA-Z])(.*)" "\\\\1:\\\\2" _WIN_SDK_NATIVE "\${OHOS_SDK_NATIVE}")
      set(CMAKE_C_COMPILER   "\${OHOS_SDK_NATIVE}/llvm/bin/clang.exe"   CACHE STRING "" FORCE)
      set(CMAKE_CXX_COMPILER "\${OHOS_SDK_NATIVE}/llvm/bin/clang++.exe" CACHE STRING "" FORCE)
      set(CMAKE_C_COMPILER_TARGET   "aarch64-linux-ohos" CACHE STRING "" FORCE)
      set(CMAKE_CXX_COMPILER_TARGET "aarch64-linux-ohos" CACHE STRING "" FORCE)
      # Do NOT set CMAKE_SYSROOT — Windows binary cannot resolve /mnt/... paths for libraries
      # Instead pass --sysroot with the Windows-style path directly in compile flags
      set(CMAKE_C_FLAGS_INIT   "-D__MUSL__ --sysroot=\${_WIN_SDK_NATIVE}/sysroot")
      set(CMAKE_CXX_FLAGS_INIT "-D__MUSL__ --sysroot=\${_WIN_SDK_NATIVE}/sysroot")
    endif()
  endif()
endif()

project(${soName})

set(POLYBIND_ROOT "\${CMAKE_CURRENT_SOURCE_DIR}/${relPolybind}")
set(POLYBIND_INCLUDE_DIR \${POLYBIND_ROOT}/include)
set(POLYBIND_NAPI_BRIDGE  \${POLYBIND_ROOT}/src/napi_bridge.cpp)
set(POLYBIND_MODULE_NAME  ${soName})

set(POLYBIND_TOOL_SOURCES
${sources.map(f => `  \${CMAKE_CURRENT_SOURCE_DIR}/${relSrc}/${f}`).join('\n')}
)

# Switch platform at configure time:
#   cmake -B build -DPOLYBIND_PLATFORM=node   .   (→ ${soName}_node.node)
#   cmake -B build -DPOLYBIND_PLATFORM=arkts  .   (→ lib${soName}.so)
if(POLYBIND_PLATFORM STREQUAL "arkts")
  include(\${POLYBIND_ROOT}/cmake/polybind-arkts.cmake)
else()
  include(\${POLYBIND_ROOT}/cmake/polybind-node.cmake)
endif()
`
  writeFileSync(join(outDir, 'CMakeLists.txt'), cmake, 'utf8')
}

function getCppSources(srcDir: string): string[] {
  try {
    return readdirSync(srcDir)
      .filter(f => f.endsWith('.cpp'))
  } catch {
    return ['polybind_entry.cpp']
  }
}

// ── Generate manifest from .ets analysis ──────────────────────────────────────
// Used when no tools.yaml exists (cases 2 and 3).
// Infers extension name from the .ets file's exported IExtension class.

export interface EtsManifestOptions {
  etsFiles: string[]
  outPath: string
  extensionName?: string
  version?: string
}

export function generateManifestFromEts(opts: EtsManifestOptions): void {
  const { etsFiles, outPath, extensionName, version } = opts

  // Attempt to extract extension name from a class like JSVMEvalExtension
  let inferredName = extensionName ?? 'unknown-extension'
  let inferredVersion = version ?? '0.1.0'
  let inferredPlatforms: string[] = ['arkts']

  for (const f of etsFiles) {
    const source = readFileSync(f, 'utf8')

    // Try to find extension name from manifest comment or class name
    const classMatch = source.match(/class\s+(\w+)\s+implements\s+IExtension/)
    if (classMatch && !extensionName) {
      // Convert PascalCase to kebab-case: JSVMEvalExtension → jsvm-eval
      const className = classMatch[1].replace(/Extension$/, '')
      inferredName = className
        .replace(/([A-Z])/g, (m, p1, offset) => (offset > 0 ? '-' : '') + p1.toLowerCase())
        .replace(/^-/, '')
    }

    // If file also has .cpp references, mark as both platforms
    const hasCppImport = /from\s+['"]lib\w+\.so['"]/.test(source)
    if (hasCppImport) {
      inferredPlatforms = ['arkts']  // Mixed: still ArkTS-only for the extension manifest
    }
  }

  // Extract tool definitions from listTools() return
  // (simple heuristic: find name: '...' patterns in a listTools function)
  const tools: Array<{ name: string; description: string }> = []

  for (const f of etsFiles) {
    const source = readFileSync(f, 'utf8')
    // Find tool names from patterns like: name: 'js_eval',
    const toolNameRe = /name\s*:\s*['"]([^'"]+)['"]\s*,/g
    const descRe = /description\s*:\s*['"]([^'"]+)['"]/

    let m: RegExpExecArray | null
    while ((m = toolNameRe.exec(source)) !== null) {
      const toolName = m[1]
      if (!toolName.startsWith('@') && !toolName.includes('/')) {
        // Looks like a tool name (not a module path)
        // Try to find the description nearby
        const nearby = source.slice(Math.max(0, m.index - 200), m.index + 200)
        const descMatch = nearby.match(descRe)
        const desc = descMatch ? descMatch[1].slice(0, 120) : `${toolName} tool`
        if (!tools.some(t => t.name === toolName)) {
          tools.push({ name: toolName, description: desc })
        }
      }
    }
  }

  const manifest: ManifestFile = {
    name: inferredName,
    version: inferredVersion,
    types: [
      {
        kind: 'toolkit',
        type: inferredName,
        platforms: inferredPlatforms as ('node' | 'arkts')[],
        schema: {
          type: 'object',
          properties: {},
          additionalProperties: false,
        },
      },
    ],
  }

  const clean = JSON.parse(JSON.stringify(manifest))
  writeFileSync(outPath, yaml.dump(clean, { lineWidth: 100 }), 'utf8')
}
