/**
 * generate.ts — Generate polymath extension artifacts from a tools.yaml descriptor
 * or from analysis of existing ArkTS files.
 *
 * Outputs:
 *   manifest.yaml               — polymath extension manifest
 *   manifest.ts                 — TypeScript import of manifest for registerExtension()
 *   PolybindExtension.js        — Node.js IExtension wrapper (case 1 only, self-contained ESM)
 *   PolybindExtension.ets       — ArkTS IExtension wrapper (case 1 only, stamped from template)
 *
 * For case 2 (mixed) and case 3 (ArkTS only), manifest files are still generated,
 * but the wrappers are the fixed .ets files (not a new generated wrapper).
 */

import { readFileSync, writeFileSync, readdirSync, realpathSync } from 'node:fs'
import { resolve, dirname, basename, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import yaml from 'js-yaml'

const __dir = dirname(fileURLToPath(import.meta.url))

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ToolsYamlConfigProperty {
  type: string
  description?: string
  default?: unknown
  env_var?: string   // If set, this config property is forwarded to process.env[env_var] at runtime
}

export interface ToolsYaml {
  extension: {
    name: string
    version: string
    description?: string
    so_name?: string        // NAPI module name; ArkTS import: `import X from 'libX.so'` (Case 1 only)
    node_entry?: {          // TypeScript extension entry (Case 3 TypeScript); triggers import-based wrapper
      module: string        //   path to the TS/JS source file, relative to tools.yaml
      export: string        //   exported class name to instantiate as extension
    }
    platforms?: string[]
    config?: {              // Extension-level config schema → manifest schema.properties
      properties?: Record<string, ToolsYamlConfigProperty>
      required?: string[]
      additionalProperties?: boolean
    }
  }
  tools: Array<{
    name: string
    description: string
    input_schema: Record<string, unknown>
  }>
}

export interface ManifestTool {
  name: string
  description: string
  input_schema: Record<string, unknown>
}

export interface ManifestTypeEntry {
  kind: string
  type: string
  description?: string
  platforms?: string[]
  schema?: Record<string, unknown>
  tools?: ManifestTool[]   // Tool list with input schemas (polybind extension to manifest format)
}

export interface ManifestFile {
  name: string
  version: string
  description?: string
  types: ManifestTypeEntry[]
}

// ── Parse tools.yaml ─────────────────────────────────────────────────────────

export function parseToolsYaml(yamlPath: string): ToolsYaml {
  const raw = readFileSync(yamlPath, 'utf8')
  return yaml.load(raw) as ToolsYaml
}

// ── Generate manifest.yaml ────────────────────────────────────────────────────

export function buildManifest(descriptor: ToolsYaml): ManifestFile {
  const cfg = descriptor.extension.config
  return {
    name: descriptor.extension.name,
    version: descriptor.extension.version,
    description: descriptor.extension.description,
    types: [
      {
        kind: 'toolkit',
        type: descriptor.extension.name,
        description: descriptor.extension.description,
        platforms: descriptor.extension.platforms as ('node' | 'arkts')[],
        schema: {
          type: 'object',
          properties: cfg?.properties ?? {},
          ...(cfg?.required?.length ? { required: cfg.required } : {}),
          additionalProperties: cfg?.additionalProperties ?? false,
        },
        tools: descriptor.tools.map(t => ({
          name: t.name,
          description: t.description,
          input_schema: t.input_schema,
        })),
      },
    ],
  }
}

export function writeManifestYaml(manifest: ManifestFile, outDir: string): void {
  // Clean up undefined fields before serializing
  const clean = JSON.parse(JSON.stringify(manifest))
  const yamlStr = yaml.dump(clean, { lineWidth: 100 })
  writeFileSync(join(outDir, 'manifest.yaml'), yamlStr, 'utf8')
}

// ── Generate manifest.ts ──────────────────────────────────────────────────────

export function writeManifestTs(manifest: ManifestFile, outDir: string): void {
  const ts = `// GENERATED by polybind-codegen — do not edit manually.
import type { ExtensionManifestFile } from '@polymath/types'

export const manifest: ExtensionManifestFile = ${JSON.stringify(manifest, null, 2)} as const
`
  writeFileSync(join(outDir, 'manifest.ts'), ts, 'utf8')
}

// ── Generate PolybindExtension.ets (ArkTS wrapper, case 1) ───────────────────

export function writeArkTSWrapper(descriptor: ToolsYaml, outDir: string): void {
  const templatePath = resolve(__dir, '../../runtime/arkts/src/PolybindExtension.ets.tmpl')
  let tmpl = readFileSync(templatePath, 'utf8')

  const soName = descriptor.extension.so_name ?? descriptor.extension.name.replace(/-/g, '_')
  tmpl = tmpl.replaceAll('{{SO_NAME}}', soName)
  tmpl = tmpl.replaceAll('{{EXTENSION_NAME}}', descriptor.extension.name)
  tmpl = tmpl.replaceAll('{{EXTENSION_VERSION}}', descriptor.extension.version)

  writeFileSync(join(outDir, 'PolybindExtension.ets'), tmpl, 'utf8')
}

// ── Generate PolybindExtension.js (Node.js wrapper, case 1) ──────────────────

export function writeNodeWrapper(descriptor: ToolsYaml, outDir: string): void {
  const manifestJson = JSON.stringify(buildManifest(descriptor), null, 2)

  // ── TypeScript entry (node_entry) ─────────────────────────────────────────
  // When tools.yaml declares `node_entry`, generate a thin import-based wrapper
  // instead of a NAPI bridge. bind.sh is responsible for copying the TS source
  // files to outDir and compiling them before this wrapper is loaded.
  const nodeEntry = descriptor.extension.node_entry
  if (nodeEntry) {
    // Convert the module path (.ts → .js) for the compiled import target.
    const jsPath = './' + nodeEntry.module.replace(/\.ts$/, '.js')
    const className = nodeEntry.export
    const js = `// GENERATED by polybind-codegen — do not edit manually.
// TypeScript entry wrapper for: ${descriptor.extension.name}
// Source: ${nodeEntry.module} → compiled to ${jsPath.slice(2)}

import { ${className} } from '${jsPath}'

export const extension = new ${className}()

export function createExtension(hub) { return new ${className}(hub) }

export const manifest = ${manifestJson}
`
    writeFileSync(join(outDir, 'PolybindExtension.js'), js, 'utf8')
    return
  }

  // ── NAPI bridge (so_name) ──────────────────────────────────────────────────
  const soName = descriptor.extension.so_name ?? descriptor.extension.name.replace(/-/g, '_')

  // Build env var mapping from tools.yaml config: { configKey: 'ENV_VAR_NAME' }
  const envMap: Record<string, string> = {}
  const props = descriptor.extension.config?.properties ?? {}
  for (const [key, prop] of Object.entries(props)) {
    if (prop.env_var) envMap[key] = prop.env_var
  }
  const envMapJson = JSON.stringify(envMap)
  const js = `// GENERATED by polybind-codegen — do not edit manually.
// Self-contained Node.js IExtension wrapper for: ${descriptor.extension.name}
// (Inlines manifest and runtime to avoid requiring additional package installs.)

import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { resolve, dirname } from 'node:path'

const __dir = dirname(fileURLToPath(import.meta.url))
const nodePath = resolve(__dir, 'src/scripts/${soName}_node.node')

const _req = createRequire(import.meta.url)
const napi = _req(nodePath)

// Generated from tools.yaml config env_var declarations
const _ENV_MAP = ${envMapJson}

class PolybindToolkit {
  constructor(napi, entryConfig) {
    this._napi = napi
    this._defs = null
    if (entryConfig) {
      for (const [key, envVar] of Object.entries(_ENV_MAP)) {
        const val = entryConfig[key]
        if (val != null) process.env[envVar] = String(val)
      }
    }
  }

  async listTools() {
    if (this._defs === null) {
      this._defs = JSON.parse(this._napi.listTools())
    }
    return this._defs
  }

  callTool(name, args, progress) {
    if (progress) return this._stream(name, args)
    return this._call(name, args)
  }

  async _call(name, args) {
    const raw = this._napi.callTool(name, JSON.stringify(args))
    const parsed = JSON.parse(raw)
    return { type: 'response', content: parsed.content, error: parsed.error }
  }

  async *_stream(name, args) {
    yield await this._call(name, args)
  }
}

export class PolybindExtension {
  async initAppSession(_appSessionId) {}
  async destroyAppSession(_appSessionId) {}
  async createObject(_appSessionId, _entry) {
    return new PolybindToolkit(napi, _entry)
  }
}

export const extension = new PolybindExtension()

export const manifest = ${manifestJson}
`
  writeFileSync(join(outDir, 'PolybindExtension.js'), js, 'utf8')
}

// ── Generate PolybindExtension.d.ts (Node.js TypeScript declarations) ────────

export function writeNodeWrapperDts(descriptor: ToolsYaml, outDir: string): void {
  const dts = `// GENERATED by polybind-codegen — do not edit manually.
import type { ExtensionManifestFile, IExtension } from '@polymath/types'

export declare const manifest: ExtensionManifestFile
export declare const extension: IExtension
export declare function createExtension(hub: unknown): IExtension
`
  writeFileSync(join(outDir, 'PolybindExtension.d.ts'), dts, 'utf8')
}

// ── Generate PolybindExtension.js (ArkTS platform Node.js-importable stub) ───
// Allows Node.js bootstrap to statically import an ArkTS extension's manifest
// without needing the HarmonyOS runtime. createObject throws if invoked.

export function writeArkTSNodeStub(descriptor: ToolsYaml, outDir: string): void {
  const manifestJson = JSON.stringify(buildManifest(descriptor), null, 2)
  const js = `// GENERATED by polybind-codegen — do not edit manually.
// ArkTS/HarmonyOS platform stub for: ${descriptor.extension.name}
// Exports manifest so this file can be imported on any platform.
// Actual execution requires the ArkTS/HarmonyOS JSVM runtime — createObject throws on Node.js.

export const manifest = ${manifestJson}

export class PolybindExtension {
  constructor(_hub) {}
  async initAppSession(_appSessionId) {}
  async createObject(_appSessionId, _entry) {
    throw new Error('${descriptor.extension.name} ArkTS extension requires the HarmonyOS/ArkTS runtime')
  }
}

export const extension = new PolybindExtension()
export function createExtension(_hub) { return new PolybindExtension(_hub) }
`
  writeFileSync(join(outDir, 'PolybindExtension.js'), js, 'utf8')
}

// ── Generate CMakeLists.txt (case 1) ─────────────────────────────────────────

export function writeCMakeLists(
  descriptor: ToolsYaml,
  srcDir: string,
  outDir: string,
  polybindRoot: string,
  noBridge = false,
): void {
  const soName = descriptor.extension.so_name ?? descriptor.extension.name.replace(/-/g, '_')
  const sources = getCppSources(srcDir)
  // Use paths relative to the output CMakeLists.txt for portability
  const relSrc = relative(outDir, srcDir).replace(/\\/g, '/')
  const relPolybind = relative(outDir, polybindRoot).replace(/\\/g, '/')

  const cmake = `# GENERATED by polybind-codegen — do not edit manually.
cmake_minimum_required(VERSION 3.14)

# ── ArkTS: detect OHOS cross-compiler BEFORE project() ───────────────────────
if(POLYBIND_PLATFORM STREQUAL "arkts")
  if(NOT DEFINED OHOS_SDK_NATIVE OR OHOS_SDK_NATIVE STREQUAL "")
    if(DEFINED ENV{OHOS_SDK_NATIVE})
      set(OHOS_SDK_NATIVE "$ENV{OHOS_SDK_NATIVE}")
    else()
      foreach(_cand
        "/mnt/d/harmonyos/DevEco Studio/sdk/default/openharmony/native"
        "/mnt/c/Users/$ENV{USER}/AppData/Local/Huawei/Sdk/openharmony/native"
        "$ENV{HOME}/harmonyos/native"
      )
        if(EXISTS "\${_cand}/llvm/bin/aarch64-unknown-linux-ohos-clang" OR EXISTS "\${_cand}/llvm/bin/clang.exe")
          set(OHOS_SDK_NATIVE "\${_cand}")
          break()
        endif()
      endforeach()
    endif()
  endif()
  if(DEFINED OHOS_SDK_NATIVE AND NOT OHOS_SDK_NATIVE STREQUAL "")
    if(CMAKE_COMMAND MATCHES "\\\\.exe$")
      # Running under cmake.exe (Windows) — shell scripts are not valid Win32 apps;
      # use clang.exe directly. OHOS_SDK_NATIVE is already a Windows-style path.
      if(EXISTS "\${OHOS_SDK_NATIVE}/llvm/bin/clang.exe")
        set(CMAKE_SYSROOT "\${OHOS_SDK_NATIVE}/sysroot" CACHE STRING "" FORCE)
        set(CMAKE_C_COMPILER   "\${OHOS_SDK_NATIVE}/llvm/bin/clang.exe"   CACHE STRING "" FORCE)
        set(CMAKE_CXX_COMPILER "\${OHOS_SDK_NATIVE}/llvm/bin/clang++.exe" CACHE STRING "" FORCE)
        set(CMAKE_C_COMPILER_TARGET   "aarch64-linux-ohos" CACHE STRING "" FORCE)
        set(CMAKE_CXX_COMPILER_TARGET "aarch64-linux-ohos" CACHE STRING "" FORCE)
        set(CMAKE_C_FLAGS_INIT   "-D__MUSL__")
        set(CMAKE_CXX_FLAGS_INIT "-D__MUSL__")
      endif()
    else()
      # Running under Linux cmake — prefer the native Linux wrapper script
      if(EXISTS "\${OHOS_SDK_NATIVE}/llvm/bin/aarch64-unknown-linux-ohos-clang")
        # Native Linux cross-compiler (accepts Linux source paths, no WSL path issues)
        set(CMAKE_C_COMPILER   "\${OHOS_SDK_NATIVE}/llvm/bin/aarch64-unknown-linux-ohos-clang"   CACHE STRING "" FORCE)
        set(CMAKE_CXX_COMPILER "\${OHOS_SDK_NATIVE}/llvm/bin/aarch64-unknown-linux-ohos-clang++" CACHE STRING "" FORCE)
        set(CMAKE_SYSROOT "\${OHOS_SDK_NATIVE}/sysroot" CACHE STRING "" FORCE)
      elseif(EXISTS "\${OHOS_SDK_NATIVE}/llvm/bin/clang.exe")
        # Windows SDK via WSL2 binfmt_misc — clang.exe called from Linux cmake
        string(REGEX MATCH "^/mnt/([a-zA-Z])" _DRIVE_MATCH "\${OHOS_SDK_NATIVE}")
        if(_DRIVE_MATCH)
          string(TOUPPER "\${CMAKE_MATCH_1}" _DRIVE_LETTER)
          string(REGEX REPLACE "^/mnt/[a-zA-Z]" "" _REST "\${OHOS_SDK_NATIVE}")
          set(_WIN_SDK_NATIVE "\${_DRIVE_LETTER}:\${_REST}")
        else()
          set(_WIN_SDK_NATIVE "\${OHOS_SDK_NATIVE}")
        endif()
        set(CMAKE_SYSROOT "\${_WIN_SDK_NATIVE}/sysroot" CACHE STRING "" FORCE)
        set(CMAKE_C_COMPILER   "\${OHOS_SDK_NATIVE}/llvm/bin/clang.exe"   CACHE STRING "" FORCE)
        set(CMAKE_CXX_COMPILER "\${OHOS_SDK_NATIVE}/llvm/bin/clang++.exe" CACHE STRING "" FORCE)
        set(CMAKE_C_COMPILER_TARGET   "aarch64-linux-ohos" CACHE STRING "" FORCE)
        set(CMAKE_CXX_COMPILER_TARGET "aarch64-linux-ohos" CACHE STRING "" FORCE)
        set(CMAKE_C_FLAGS_INIT   "-D__MUSL__")
        set(CMAKE_CXX_FLAGS_INIT "-D__MUSL__")
      endif()
    endif()
  endif()
endif()

project(${soName})

set(POLYBIND_ROOT "\${CMAKE_CURRENT_SOURCE_DIR}/${relPolybind}")
get_filename_component(POLYBIND_ROOT "\${POLYBIND_ROOT}" ABSOLUTE)
set(POLYBIND_INCLUDE_DIR \${POLYBIND_ROOT}/include)
${noBridge ? '# noBridge: POLYBIND_NAPI_BRIDGE left empty (Case 2 — sources implement NAPI directly)' : 'set(POLYBIND_NAPI_BRIDGE  ${POLYBIND_ROOT}/src/napi_bridge.cpp)'}
set(POLYBIND_MODULE_NAME  ${soName})

set(POLYBIND_TOOL_SOURCES
${sources.map(f => {
    // Resolve symlinks; emit Windows path (X:/...) when on a mounted drive so
    // cmake.exe / clang.exe can open the file without following WSL symlinks.
    try {
      const real = realpathSync(join(srcDir, f))
      const m = real.match(/^\/mnt\/([a-zA-Z])\/(.+)$/)
      if (m) return `  ${m[1].toUpperCase()}:/${m[2]}`
    } catch {}
    return `  \${CMAKE_CURRENT_SOURCE_DIR}/${relSrc}/${f}`
  }).join('\n')}
)

# Switch platform at configure time:
#   cmake -B build -DPOLYBIND_PLATFORM=node   .   (→ ${soName}_node.node)
#   cmake -B build -DPOLYBIND_PLATFORM=arkts  .   (→ lib${soName}.so)
if(POLYBIND_PLATFORM STREQUAL "arkts")
  include(\${POLYBIND_ROOT}/cmake/polybind-arkts.cmake)
else()
  include(\${POLYBIND_ROOT}/cmake/polybind-node.cmake)
endif()
`
  writeFileSync(join(outDir, 'CMakeLists.txt'), cmake, 'utf8')
}

function getCppSources(srcDir: string): string[] {
  // Recursively find all .cpp files, returning paths relative to srcDir.
  function walk(dir: string, prefix: string): string[] {
    const results: string[] = []
    try {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const rel = prefix ? prefix + '/' + entry.name : entry.name
        if (entry.isDirectory()) {
          results.push(...walk(join(dir, entry.name), rel))
        } else if (entry.name.endsWith('.cpp')) {
          results.push(rel)
        }
      }
    } catch { /* ignore unreadable dirs */ }
    return results
  }
  const found = walk(srcDir, '')
  return found.length > 0 ? found : ['polybind_entry.cpp']
}

// ── Generate manifest from .ets analysis ──────────────────────────────────────
// Used when no tools.yaml exists (cases 2 and 3).
// Infers extension name from the .ets file's exported IExtension class.

export interface EtsManifestOptions {
  etsFiles: string[]
  outPath: string
  extensionName?: string
  version?: string
}

export function generateManifestFromEts(opts: EtsManifestOptions): void {
  const { etsFiles, outPath, extensionName, version } = opts

  // Attempt to extract extension name from a class like JSVMEvalExtension
  let inferredName = extensionName ?? 'unknown-extension'
  let inferredVersion = version ?? '0.1.0'
  let inferredPlatforms: string[] = ['arkts']

  for (const f of etsFiles) {
    const source = readFileSync(f, 'utf8')

    // Try to find extension name from manifest comment or class name
    const classMatch = source.match(/class\s+(\w+)\s+implements\s+IExtension/)
    if (classMatch && !extensionName) {
      // Convert PascalCase to kebab-case: JSVMEvalExtension → jsvm-eval
      const className = classMatch[1].replace(/Extension$/, '')
      inferredName = className
        .replace(/([A-Z])/g, (m, p1, offset) => (offset > 0 ? '-' : '') + p1.toLowerCase())
        .replace(/^-/, '')
    }

    // If file also has .cpp references, mark as both platforms
    const hasCppImport = /from\s+['"]lib\w+\.so['"]/.test(source)
    if (hasCppImport) {
      inferredPlatforms = ['arkts']  // Mixed: still ArkTS-only for the extension manifest
    }
  }

  // Extract tool definitions from listTools() return
  // (simple heuristic: find name: '...' patterns in a listTools function)
  const tools: Array<{ name: string; description: string }> = []

  for (const f of etsFiles) {
    const source = readFileSync(f, 'utf8')
    // Find tool names from patterns like: name: 'js_eval',
    const toolNameRe = /name\s*:\s*['"]([^'"]+)['"]\s*,/g
    const descRe = /description\s*:\s*['"]([^'"]+)['"]/

    let m: RegExpExecArray | null
    while ((m = toolNameRe.exec(source)) !== null) {
      const toolName = m[1]
      if (!toolName.startsWith('@') && !toolName.includes('/')) {
        // Looks like a tool name (not a module path)
        // Try to find the description nearby
        const nearby = source.slice(Math.max(0, m.index - 200), m.index + 200)
        const descMatch = nearby.match(descRe)
        const desc = descMatch ? descMatch[1].slice(0, 120) : `${toolName} tool`
        if (!tools.some(t => t.name === toolName)) {
          tools.push({ name: toolName, description: desc })
        }
      }
    }
  }

  const manifest: ManifestFile = {
    name: inferredName,
    version: inferredVersion,
    types: [
      {
        kind: 'toolkit',
        type: inferredName,
        platforms: inferredPlatforms as ('node' | 'arkts')[],
        schema: {
          type: 'object',
          properties: {},
          additionalProperties: false,
        },
      },
    ],
  }

  const clean = JSON.parse(JSON.stringify(manifest))
  writeFileSync(outPath, yaml.dump(clean, { lineWidth: 100 }), 'utf8')
}
